## Data Encryption and Decryption

- Data Encryption
                   Encryption is a security method in which information is encoded in such a way that only authorized user can read it. It uses encryption alogorithm to generate ciphertext that can only be read if decrypted

- Data Decryption
                  Decryption is the process of taking encoded or encrypted text and converting it back into the text that you or the computer can read and understand 

- Types
      Symmetric (private key): It uses a single key that will be shared among the people who need to receive the message
- Asymmetric (public key):
                            Asymmetrical encryption uses a pair of public key and a private key to encrypt and decrypt messages

 - Write a function to generate key for encryption


In [6]:
# Function to generate key for encryption
keypath ='DataFiles/key.txt'
def generatekey(keypath):
    with open(keypath,'w') as f:
        for i in range(10):
            if i < 6:
                f.write(str(i)+ ' '+str(i+4)+'\n')
            else:
                f.write(str(i)+ ' '+str(i-6)+'\n')
    return
generatekey(keypath)


In [17]:
#Function to decrypt a DataFile
keyfile = 'DataFiles/key.txt'
def dictionarykeyFile(keyfile):
    key = {}
    with open(keyfile,'r') as f:
        for line in f:
            line = line.split()
            key[line[0]] = line[1]
    return key
def encryptMarksData(datafile, keyfile):
    #construct a dictionary for key data
    key = dictionarykeyFile(keyfile)
    with open(datafile,'r') as f:
        filedata = f.read().split('\n')
    with open('DataFiles/encryptedMarks.txt','w') as f:
        for mark in filedata:
            line = ''
            for n in mark:
                line += key[n]
                f.write(line+'\n')
    return
datafile = 'DataFiles/marks.txt'
encryptMarksData(datafile, keyfile)

In [20]:
# Function to decrypt an encrypted a file
def decryptedMarksData(encryptedfile,keyfile):
    key = dictionarykeyFile(keyfile)
    newkey ={}
    for key, value in key.items():
        newkey[value] = key
    with open(encryptedfile, 'r') as f:
        encrypteddata = f.read().split('\n')
    with open('DataFiles/decryptedMarks.txt','w') as f:
        for encryptedmark in encrypteddata:
            line = ''
            for n in encryptedmark:
                line += newkey[n]
                f.write(line + '\n')
    return 
encryptedfile = 'DataFiles/encryptedMarks.txt'
import timeit
st = timeit.default_timer()
decryptedMarksData(encryptedfile,keyfile)
print(timeit.default_timer()-st)

0.1021241920002467


### Python Libraries For Data Science


In [ ]:
- Data Science is the process of deriving knowledge and insights from a huge and diverse 

In [ ]:
- program to print the given list into an array using numpy

### Numpy

#### numpy arrays

In [4]:
import numpy as np
array_2d = np.array([[2,3,4],[5,8,7]])
print(array_2d)

[[2 3 4]
 [5 8 7]]


- program to print the given list into an array using numpy

In [3]:
import numpy as np
li = (1,2,3,'z')
a = np.array(li)
print(a)

['1' '2' '3' 'z']


In [7]:
import numpy as np
li = (1,2,3,4.0)
a = np.array(li)
a


array([1., 2., 3., 4.])

- for example, the following code print 1D array between 1 to 15

In [9]:
import numpy as np
a = np.arange(15)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


- for example, the following code print 1000 numbers in a 1D array

In [12]:
import numpy as np
a2 = np.arange(100,10000)
a2

array([ 100,  101,  102, ..., 9997, 9998, 9999])

In [11]:
a2 = np.arange(10000).reshape(100,100)
a2

array([[   0,    1,    2, ...,   97,   98,   99],
       [ 100,  101,  102, ...,  197,  198,  199],
       [ 200,  201,  202, ...,  297,  298,  299],
       ...,
       [9700, 9701, 9702, ..., 9797, 9798, 9799],
       [9800, 9801, 9802, ..., 9897, 9898, 9899],
       [9900, 9901, 9902, ..., 9997, 9998, 9999]])

### inspect the structure and content of array using "ndarrays"


- create a 2D Array and inspect size,shape,dimenshions, ans dtype of the array

In [14]:
import numpy
array1 = np.random.randint(0,2,size=(3,3))
array1[2][2]
print('shape:',array1.shape)
print('size:',array1.size)
print('Dtype:',array1.dtype)
print('ItemSize:',array1.itemsize)
print('Data:',array1.data)
array1

shape: (3, 3)
size: 9
Dtype: int32
ItemSize: 4
Data: <memory at 0x000001D066308990>


array([[1, 0, 0],
       [1, 1, 0],
       [1, 0, 0]])

In [15]:
array1 =[[1,2,3,4],[5,6,7,8]]
a1 = np.array(array1)
a1

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [18]:
import numpy as np
arr = np.arange(15).reshape(3,5)
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

- reverese thwe array using slicing

In [19]:
arr[::-1]

array([[10, 11, 12, 13, 14],
       [ 5,  6,  7,  8,  9],
       [ 0,  1,  2,  3,  4]])

- create a an array of 1's . Take a list & covert it into 3D array and add 1 to each element in an array

In [21]:
np.ones?

In [20]:
import numpy as np
a = np.ones((3,3))
print(a)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [22]:
b=[[1,2,3],[10,20,30],[11,22,33]]
c=np.array(b)
c

array([[ 1,  2,  3],
       [10, 20, 30],
       [11, 22, 33]])

In [25]:
d = c+1
d,

(array([[ 2,  3,  4],
        [11, 21, 31],
        [12, 23, 34]]),)

- we can perform arthimetic operators in Numpy like addition,substraction ets,..,and of course log,sin,cos,etc

In [26]:
a = np.arange(1,7).reshape(2,3)
b = np.arange(5,11).reshape(2,3)
print(a,)
print(b,'\n')
print(a+b)
print(a/b)

[[1 2 3]
 [4 5 6]]
[[ 5  6  7]
 [ 8  9 10]] 

[[ 6  8 10]
 [12 14 16]]
[[0.2        0.33333333 0.42857143]
 [0.5        0.55555556 0.6       ]]
